### ISSUE TITLE
why not use T.constant in mnist.py load_data()?

### ISSUE THREAD

**Issue by r2007** [benanne/Lasagne#195]
Like this:
```
X_train=theano.shared(lasagne.utils.floatX(X_train)),
```
can it be like this?
```
X_train=T.constant(lasagne.utils.floatX(X_train)),
```
My intuition, constant will be better than shared, at least not bad.

**Comment by f0k** [comment]
Shared variables are immediately copied to the GPU:
```
>>> import numpy as np
>>> import theano
Using gpu device 0: GeForce GT 640
>>> x = np.random.randn(100,100).astype(np.float32)
>>> x_shared = theano.shared(x)
>>> x_shared.type
CudaNdarrayType(float32, matrix)
```

Constants are not:
```
>>> x_const = theano.tensor.constant(x)
>>> x_const.type
TensorType(float32, matrix)
```

On compilation, constants may still get moved to GPU:
```
>>> f = theano.function([], theano.sandbox.cuda.as_cuda_ndarray_variable(x_const))
>>> theano.printing.debugprint(f)
DeepCopyOp [@A] ''   0
 |CudaNdarrayConstant{[[...]]}
```

But I don't think there's a benefit to it. The deeplearning tutorial also uses shared variables for the dataset: http://deeplearning.net/tutorial/logreg.html#putting-it-all-together

An advantage of using shared variables is that you can replace their content in between Theano function calls, e.g., if your dataset is too large to fit into GPU memory at once. At some point we will have examples demonstrating this.

**Comment by r2007** [comment]
I see. Thanks for your reply.
Yes, in this case using constant can not get benefit to it. And assume the 1st hidden layer is a pad or maxpool type, does theano calculate it first as a new constant for the later calculation if all symbols are constant when create function? So, using constant will be better than shared?

**Comment by r2007** [comment]
I think theano should add a new type symbol, share&constant. that It can be shared for multiple functions and also be a constant symbol, or just let constant become shared automatically.

**Comment by f0k** [comment]
> And assume the 1st hidden layer is a pad or maxpool type, does theano calculate it first as a new constant for the later calculation if all symbols are constant when create function?

Theano does have a constant folding optimization, but I don't know if it is applied to convolutional or pooling operations. You can try by compiling a function and printing its graph using `theano.printing.debugprint` as I did above. Anyway, it's probably better to do such preprocessing steps explicitly in your code rather than hoping for it to happen during compilation of the training function.

This discussion is outside the scope of Lasagne now, and this Issue is closed because we'll leave the example as it is. For the future, please discuss Lasagne-related questions at [lasagne-users](https://groups.google.com/forum/#!forum/lasagne-users), and Theano-related questions at [theano-users](https://groups.google.com/forum/#!forum/theano-users), to leave the issue tracker for bug reports and pull requests. Thanks!
