### ISSUE TITLE
Which versions of Python / numpy / Theano should be supported?

### ISSUE THREAD

**Issue by benanne** [benanne/Lasagne#23]
Which versions of Python, numpy and Theano should we support? It's probably okay to rely on Theano 0.6+, but what versions of Python and numpy are in common use at the moment? I would be in favor of not burdening the project with too much 'backward compatibility', so requiring recent Python and numpy versions is okay for me.

Also, what about Python 3? Should we support this? Afaik the scientific community is still relying mostly on Python 2 (and that's what I use), but Python 3 support is probably desirable in the interest of future-proofing the library.

**Comment by jseabold** [comment]
FWIW, many libraries either rely on, or ship with a subset of, the [six](https://pypi.python.org/pypi/six) library. Using it you can target Python 2 and Python 3 with a single codebase.

**Comment by benanne** [comment]
Thanks, that sounds like something we should look into.

**Comment by ebattenberg** [comment]
I've personally been attempting a switchover to python 3.  I've run into a few snags with Theano (you can't use it in "setup.py develop" mode, have to "setup.py install" so the 2to3 script is run). 

For now, should we attempt something similar with Lasagne, i.e., run the 2to3 script when installing for python3?  Then we could at least see if the current python2 code is forward compatible?

**Comment by ebattenberg** [comment]
@jseabold Which popular libraries already rely on six?

**Comment by ebattenberg** [comment]
From the python 2 to 3 porting guide: https://docs.python.org/3/howto/pyporting.html

They suggest using "modernize" and "futurize".  

Modernize (http://python-modernize.readthedocs.org/en/latest/) is a simple script that inserts all the best py2/3 compability practices for existing python 2 code.  

Futurize (http://python-future.org/automatic_conversion.html) goes a bit further by adding some imports for even stronger py3 compatibility with the option of using the extra "future" module for near complete py3 compatibility.  

Futurize seems a bit like the "six" library that @jseabold suggested.

**Comment by dnouri** [comment]
So this write up by Armin Ronacher (the Flask guy) looks like a very useful resource with lots of advice on how to do the porting to Python 3: http://lucumr.pocoo.org/2013/5/21/porting-to-python-3-redux/

I guess it wouldn't be a mistake to try and improve test coverage before we port to Python 3.

**Comment by dnouri** [comment]
Oh I'm seeing that @f0k wrote similar things about a compatibility module back in September.

**Comment by jseabold** [comment]
Scikit-learn, numpy, scipy, statsmodels, pandas all rely on six or a variation thereof that I know of off the top of my head. Maybe IPython too. You can either copy what you need instead of adding the six dependency explicitly. I think scikit-learn just plops six.py into an `externals` directory.

This is the big PR that moved from `use_2to3` in setuptools to using compat modules in statsmodels. I don't find the PRs for other projects with a quick search.

https://github.com/statsmodels/statsmodels/pull/1520

We only rely on these types of things to be compatible with both 2.7 - 3.4.

https://github.com/statsmodels/statsmodels/blob/master/statsmodels/compat/python.py

I think you can run the `2to3` script over your code to show you where incompatibilities are, then fix them by importing the `compat` functions. Kind of a chore, but it's doable over a weekend and then you don't have to think about it again. Setting up python 3 build on travis (or whatever) will complain, if Python 2 only stuff creeps in.

**Comment by jseabold** [comment]
FWIW, I haven't run in to any snags yet just using `use_2to3` in lasagne. I had to rewrite a couple of things in nolearn.lasagne, but it was mostly format/str stuff and relying on integer division.

**Comment by benanne** [comment]
We're supporting python 2 and python 3 officially now, so I'll close this.
